slug: python-video-bridge-user-online
name: Отслеживаем пользователей онлайн.
meta_title:  Отслеживаем пользователей онлайн.
meta_keywords:  Отслеживаем пользователей онлайн.
meta_description:  Отслеживаем пользователей онлайн.
is_active: true
tags: python video django celery socketio
created: 2021-02-26
desc:
      Контролируем подключения по веб-сокетам.
files:

    -
        file:  4-users-online.md
        title: Отслеживаем пользователей онлайн.
        meta_title: Отслеживаем пользователей онлайн.
        meta_description: Отслеживаем пользователей онлайн.
        meta_keywords: Отслеживаем пользователей онлайн.
        desc: 
        order: 1
        youtube: https://www.youtube.com/embed/TXDyszpswwY
