from .index import *
from .login import *
from .logout import *
from .courses import *
from .set_lang import *
from .buy_course import *
from .pay_success import *
from .pay_process import *
from .prepay import *
from .oferta import *
from .delivery import *
from .confident import *
from .about import about
from .pay_kursak import *
from .pay_course_process import *