slug: python-video-bridge-ice
name: Обмен ICE кандидатами.
meta_title: Обмен ICE кандидатами.
meta_keywords: Обмен ICE кандидатами.
meta_description: Обмен ICE кандидатами.
is_active: true
tags: python video django webrtc ice
created: 2021-03-01
desc:
      Передаем ICE кандидатов по сигнальному серверу.
files:

    -
        file:  9-ice-candidate.md
        title: Обмен ICE кандидатами.
        meta_title: Обмен ICE кандидатами.
        meta_description: Обмен ICE кандидатами.
        meta_keywords: Обмен ICE кандидатами.
        desc: 
        order: 1
        youtube: https://www.youtube.com/embed/haBY63ZWXag
