# Generated by Django 3.0.7 on 2020-09-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200719_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='video',
            field=models.CharField(blank=True, max_length=250, verbose_name='Video'),
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('lessons', models.ManyToManyField(to='course.Lesson', verbose_name='Content')),
            ],
        ),
    ]
