# Generated by Django 3.0.7 on 2020-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200719_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video',
            field=models.CharField(blank=True, max_length=250, verbose_name='Video'),
        ),
    ]
