# Generated by Django 3.0.7 on 2020-09-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200913_1607'),
        ('course', '0006_auto_20200911_0843'),
    ]

    operations = [
    ]
