# Generated by Django 3.0.7 on 2020-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_merge_20200914_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is new?'),
        ),
    ]
