# Generated by Django 3.0.7 on 2020-09-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200914_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
