# Generated by Django 3.0.7 on 2020-09-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_subscription_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
