# Generated by Django 3.0.7 on 2020-11-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_lesson_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
