# Generated by Django 3.0.7 on 2021-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
