# Generated by Django 3.0.7 on 2021-09-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='variants',
            field=models.CharField(blank=True, max_length=250, verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='desc',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='lesson',
            field=models.ManyToManyField(to='course.Lesson', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='емейл'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
    ]
