# Generated by Django 3.0.7 on 2021-09-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20210912_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
