# Generated by Django 3.0.7 on 2021-09-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_lab_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='text',
        ),
    ]
