# Generated by Django 3.0.7 on 2021-10-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_kursak'),
    ]

    operations = [
        migrations.AddField(
            model_name='kursak',
            name='name_slug',
            field=models.CharField(blank=True, max_length=250, verbose_name='Slug'),
        ),
    ]
