# Generated by Django 3.0.7 on 2022-07-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lang',
            field=models.CharField(default='ua', max_length=5),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is published?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='kursak',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='variants',
            field=models.CharField(blank=True, max_length=250, verbose_name='Variants'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='desc',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is new?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='lesson',
            field=models.ManyToManyField(to='course.Lesson', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name'),
        ),
    ]
