# Generated by Django 3.0.7 on 2023-08-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20220720_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='alias',
            field=models.CharField(default='', max_length=250),
        ),
    ]
