slug: js-practic-animate
name: Анимация. Организация виртуального мира аркадной игры.
meta_title: Анимация. Организация виртуального мира аркадной игры.
meta_keywords: Анимация. Организация виртуального мира аркадной игры.
meta_description: Практические задачи. Анимация.
is_active: true
tags: js javascript animation
desc:
        
    Делаем движек аркадной игры на таймерах.

files:

    -
        file:     js-arcade.md
        title: Организация виртуального мира аркадной игры.
        meta_title: Организация виртуального мира аркадной игры.
        meta_description: Организация виртуального мира аркадной игры.
        meta_keywords: Организация виртуального мира аркадной игры.
        desc:


    -
        file:     dz.md
        title: Домашнее задание.
        meta_title: Домашнее задание.
        meta_description: Домашнее задание.
        meta_keywords: Домашнее задание.
        desc:
