is_active: true
title: Фронтенд разработка на языке JavaScript.

desc: |

    Базовые навыки работы с сценариями на языке JavaScript.
    Использование библиотеки jQuery. 
    Приемы написания приложений в браузере.

  
meta_title: Фронтенд разработка на языке JavaScript.
meta_keywords: js jQuery 
meta_description: Фронтенд разработка на языке JavaScript.
order: 1
