is_active: true
title: Основы работы с Linux.
desc: |

    <p>Курс описывает основы работы в среде Linux на основе Debian.</p> 
    Приемы программирования на языках Bash и Python в этой среде.

meta_title: Основы работы с Linux.
meta_keywords: Основы работы с Linux.
meta_description: Основы работы с Linux.
