# Generated by Django 3.0.7 on 2021-09-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_lab'),
        ('student', '0004_student2course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlink', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='labs')),
                ('is_approved', models.BooleanField(default=False)),
                ('mark', models.IntegerField(default=0)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
