# Generated by Django 3.0.7 on 2021-09-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student2lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2lab',
            name='file',
            field=models.FileField(blank=True, help_text='File or zip archive', null=True, upload_to='labs'),
        ),
        migrations.AlterField(
            model_name='student2lab',
            name='gitlink',
            field=models.CharField(help_text='Link to the git repo', max_length=250),
        ),
    ]
