# Generated by Django 3.0.7 on 2021-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210912_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2lab',
            name='file',
            field=models.FileField(blank=True, help_text='Файл или zip архив.', null=True, upload_to='labs'),
        ),
        migrations.AlterField(
            model_name='student2lab',
            name='gitlink',
            field=models.CharField(help_text='Ссылка на репозиторий.', max_length=250),
        ),
    ]
