# Generated by Django 3.0.7 on 2021-10-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_lab_text'),
        ('student', '0008_student2lab_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2lab',
            name='text',
            field=models.TextField(blank=True, help_text='Text answer. For example your source code.', null=True),
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('mark', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
        ),
    ]
