# Generated by Django 3.0.7 on 2021-10-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentpayment_kursak'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='type',
            field=models.CharField(choices=[('course', 'course'), ('kursak', 'kursak')], default='course', max_length=9),
        ),
    ]
