# Generated by Django 3.0.7 on 2022-05-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_examquestion_student2examquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='alias',
            field=models.CharField(blank=True, max_length=250, verbose_name='Alias'),
        ),
    ]
