# Generated by Django 3.0.7 on 2022-05-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_exam_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='student2examquestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Exam'),
        ),
    ]
