# Generated by Django 3.0.7 on 2022-05-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_student2examquestion_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2ExamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(blank=True, null=True, upload_to='exam_answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
