# Generated by Django 3.0.7 on 2022-05-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student2examanswer_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='text',
            field=models.TextField(blank=True, max_length=250, verbose_name='Текст'),
        ),
    ]
