# Generated by Django 3.0.7 on 2022-05-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_lessonpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.IntegerField(default=100),
        ),
    ]
