# Generated by Django 3.0.7 on 2022-06-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_cost'),
        ('student', '0027_coursepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
