# Generated by Django 3.0.7 on 2022-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20220603_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
