# Generated by Django 3.0.7 on 2022-07-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_coursepayment_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='text',
            field=models.TextField(blank=True, max_length=250, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='student2lab',
            name='file',
            field=models.FileField(blank=True, help_text='File or zip archive', null=True, upload_to='labs'),
        ),
        migrations.AlterField(
            model_name='student2lab',
            name='gitlink',
            field=models.CharField(help_text='Link to the git repo', max_length=250),
        ),
    ]
