slug: linux-server-setup
name: Первичная настройка сервера.
meta_title: Первичная настройка сервера.
meta_keywords: Первичная настройка сервера.
meta_description: Первичная настройка сервера.
is_active: true
tags: linux bash nginx server
desc: 
    Настраиваем сервер на базе Ubuntu.
    Лекция для ХНТУ.

        
files:

    -
        file:    linux-server-setup.md
        title: Первичная настройка сервера.
        meta_title: Первичная настройка сервера.
        meta_description: Первичная настройка сервера.
        meta_keywords: 'bash'
        desc: 
        youtube: https://www.youtube.com/embed/tIMZLI8VSlc
        order: 1

    -
        file:    dz.md
        title: Задание.
        meta_title: Первичная настройка сервера.
        meta_description: Первичная настройка сервера.
        meta_keywords: 'bash'
        desc: 
        order: 2
        

