from .profile import *
from .registration import *
from .cabinet import *
from .join_course import *
from .detail_course import *
from .detail_lesson import *
from .labs import *
from .replanish import *
from .detail_lab import * 
from .login import *
from .detail_kursak import *
from .exam_pass import *
from .mygroup import *
from .invite import *
from .newlesson import *
from .paylesson import *
from .pay_course import *
from .paidlogin import *
from .detail_topic import *