from .profile import *
from .registration import *
from .cabinet import *
from .join_course import *
from .detail_course import *
from .detail_lesson import *
from .labs import *
from .replanish import *
from .detail_lab import * 