slug: linux-vbox
name: Виртуальная машина Virtual Box.
meta_title: Виртуальная машина Virtual Box.
meta_keywords: Виртуальная машина Virtual Box.
meta_description: Виртуальная машина Virtual Box.
is_active: true
tags: linux bash vbox
desc: |

        
files:

    -
        file:    vbox-start.md
        title: Виртуальная машина Virtual Box.
        meta_title: Виртуальная машина Virtual Box.
        meta_description: Виртуальная машина Virtual Box.
        meta_keywords: 'bash vbox'
        desc: 

