slug: bash-analize-cat-find
name: BASH. Анализ системы.
meta_title:  BASH. Анализ системы.
meta_keywords: BASH. Анализ системы.
meta_description:  BASH. Анализ системы.
is_active: true
tags: linux uwsgi asgi
desc:
       Ищем файлы. Смотрим логи.
files:

    -
        file:  bash-analize-cat-find.md
        title: BASH. Анализ системы.
        meta_title: BASH. Анализ системы.
        meta_description: BASH. Анализ системы.
        meta_keywords: BASH. Анализ системы.
        desc: 
