# Generated by Django 3.0.7 on 2021-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentor2course'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor2course',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
