# Generated by Django 3.0.7 on 2022-05-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student2examanswer_exam'),
        ('course', '0021_kursak_name_slug'),
        ('mentor', '0003_mentor2course_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor2Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentGroup')),
            ],
        ),
    ]
