# Generated by Django 3.0.7 on 2022-05-28 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_mentor2group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor2group',
            name='course',
        ),
        migrations.AddField(
            model_name='mentor2group',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor.Mentor'),
        ),
    ]
