# Generated by Django 3.0.7 on 2022-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_auto_20220528_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
