# Generated by Django 3.0.7 on 2022-05-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_kursak_name_slug'),
        ('mentor', '0010_invitation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
