slug: linux-nginx
name: Веб сервер nginx.
meta_title: Веб сервер nginx.
meta_keywords: Веб сервер nginx.
meta_description: Веб сервер nginx.
is_active: true
tags: linux bash nginx
desc: 
    Настройка виртуальных хостов.

        
files:

    -
        file:    linux-nginx.md
        title: Настройка виртуальных хостов nginx.
        meta_title: Настройка виртуальных хостов nginx.
        meta_description: Настройка виртуальных хостов nginx.
        meta_keywords: 'bash nginx'
        desc: 
        youtube: https://www.youtube.com/embed/vY1tQYa0ax0
        order: 1
        
    -
        file:    dz.md
        title: Задание.
        meta_title: Настройка виртуальных хостов nginx.
        meta_description: Настройка виртуальных хостов nginx.
        meta_keywords: 'bash nginx'
        desc:         
        order: 2
