slug: bash-proc
name: Процессы.
meta_title: Процессы.
meta_keywords: Процессы.
meta_description: Процессы.
is_active: true
tags: linux bash process file-system
desc: |

        
files:

    -
        file:     'bash-process.md'
        title: 'Управление процессами.'
        meta_title: 'Управление процессами.'
        meta_description:   'Управление процессами.'
        meta_keywords: 'bash process'
        desc: 

    -
        file:     'bash-fs.md'
        title: Файловая система.
        meta_title: Файловая система.
        meta_description:  Файловая система.
        meta_keywords: 'bash process'
        desc: 
      
