slug: js-oop-module-factory
name: ООП. Паттерны Модуль и Фабрика.
meta_title: ООП. Паттерны Модуль и Фабрика.
meta_keywords: ООП. Паттерны Модуль и Фабрика.
meta_description: ООП. Паттерны Модуль и Фабрика.
is_active: true
tags: js javascript oop pattern module fabric
desc:
    Открываем порождающие паттерны.

files:

    -
        file:     js-oop-module-factory.md
        title: ООП. Паттерны Модуль и Фабрика.
        meta_title: ООП. Паттерны Модуль и Фабрика.
        meta_description: ООП. Паттерны Модуль и Фабрика.
        meta_keywords: ООП. Паттерны Модуль и Фабрика.
        desc:

