slug: js-typescript-start
name: Typescript. Начало работы.
meta_title: Typescript. Начало работы.
meta_keywords: Typescript. Начало работы.
meta_description: Typescript. Начало работы.
is_active: true
tags: js javascript typescript
desc:
        
files:
    -
        file:     js-typescript-start.md
        title: Typescript. Начало работы.
        meta_title: Typescript. Начало работы.
        meta_description: Typescript. Начало работы.
        meta_keywords: Typescript. Начало работы.
        desc: 

   
      
