slug: js-obj-arr-str
name: Объекты. Массивы. Строки.
meta_title: Объекты. Массивы. Строки.
meta_keywords: Объекты. Массивы. Строки.
meta_description: Объекты. Массивы. Строки.
is_active: true
tags: js javascript object array string
desc: 
        
files:
    -
        file:     js-obj-arr-str.md
        title: Объекты. Массивы. Строки.
        meta_title: Объекты. Массивы. Строки.
        meta_description: Объекты. Массивы. Строки.
        meta_keywords: Объекты. Массивы. Строки.
        desc: 

    -
        file:     dz.md
        title: Домашнее задание.
        meta_title: Домашнее задание.
        meta_description: Домашнее задание.
        meta_keywords: Домашнее задание.
        desc: 

