slug: linux-docker-start
name: Начало работы с Doker.
meta_title: Начало работы с Doker.
meta_keywords: Начало работы с Doker.
meta_description: Начало работы с Doker.
is_active: true
tags: linux bash doker
desc: 
    Собираем первый образ и контейнер. 

files:

    -
        file:    linux-docker-start.md
        title: Начало работы с Doker.
        meta_title: Начало работы с Doker.
        meta_description: Начало работы с Doker.
        meta_keywords: 'linux doker'
        desc: 
        youtube: https://www.youtube.com/embed/FR35eS5065k

    -
        file:    linux-docker-dj-bd.md
        title:  Django и PostgreSQL с Doker.
        meta_title: Джаного и база данных с Doker.
        meta_description: Джаного и база данных с Doker.
        meta_keywords: 'linux django doker'
        desc: 

    -
        file:    linux-docker-nginx.md
        title:  Nginx с Doker.
        meta_title: Nginx с Doker.
        meta_description: Nginx с Doker.
        meta_keywords: 'linux nginx doker'
        desc:

    -
        file:    linux-docker-flask.md
        title:  Flask с Doker.
        meta_title: Flask с Doker.
        meta_description: Flask с Doker.
        meta_keywords: 'linux flask doker'
        desc:

