slug: js-oop
name: Основы ООП в Javascript.
meta_title: Основы ООП в Javascript.
meta_keywords: Основы ООП в Javascript.
meta_description: Основы ООП в Javascript.
tags: js javascript oop
is_active: true
desc:
        
files:

    -
        file:     js-oop.md
        title: ООП. В javascript.
        meta_title: ООП. В javascript.
        meta_description: ООП. В javascript.
        meta_keywords: ООП. В javascript.
        desc:

