slug: js-react
name: ReactJs начало.
meta_title: ReactJs начало.
meta_keywords: ReactJs начало.
meta_description: ReactJs начало.
is_active: true
tags: js javascript react
desc:

files:

    -
        file:     js-react-start.md
        title: ReactJs начало.
        meta_title: ReactJs начало.
        meta_description: ReactJs начало.
        meta_keywords: ReactJs начало.
        desc:
        youtube: https://www.youtube.com/embed/JzPQL6CjGJg
