slug: dj-react-momorepo
name: Фронтенд. Многопроектное приложение.
meta_title: Многопроектное приложение.
meta_keywords: Многопроектное приложение.
meta_description: Многопроектное приложение.
is_active: true
tags: dart
desc:
    Создаем многопроектное приложение на React и Django.

files:

    -
        file:     dj-react-momorepo.md
        title: Многопроектное приложение.
        meta_title: Многопроектное приложение.
        meta_description: Многопроектное приложение.
        meta_keywords: Многопроектное приложение.
        desc:

