slug: js-fp
name: Функциональное программирование.
meta_title: Функциональное программирование.
meta_keywords:  Функциональное программирование.
meta_description: Функциональное программирование.
is_active: true
tags: js javascript functional-programming
desc:
        
files:

    -
        file:     fp-pure-func.md
        title: Чистые функции.
        meta_title: Чистые функции.
        meta_description: Чистые функции.
        meta_keywords: Чистые функции.
        desc: 

    -
        file:     fp-sortby.md
        title: Сортировка объектов.
        meta_title: Сортировка объектов.
        meta_description: Сортировка объектов.
        meta_keywords: Сортировка объектов.
        desc: 


    -
        file:   dz.md
        title: Домашнее задание. Чистые функции.
        meta_title: Домашнее задание. Чистые функции.
        meta_description: Домашнее задание. Чистые функции.
        meta_keywords: Домашнее задание. Чистые функции.
        desc: 

   
      
