slug: linux-python-ci 
name: Непрерывная интеграция.
meta_title: Непрерывная интеграция.
meta_keywords: Непрерывная интеграция.
meta_description: Непрерывная интеграция.
is_active: true
tags: linux python ci
desc: 
    Строим сервер непрерывной интеграции на python.

files:

    -
        file:    python-ci.md
        title: Cервер непрерывной интеграции на python.
        meta_title: Cервер непрерывной интеграции на python.
        meta_description: Cервер непрерывной интеграции на python.
        meta_keywords: 'python ci'
        desc: 

