slug: linux-regex
name: BASH. Регулярные выражения.
meta_title: BASH. Регулярные выражения.
meta_keywords: BASH. Регулярные выражения.
meta_description: BASH. Регулярные выражения.
is_active: true
tags: linux bash regex grep
desc: 
    Собираем первый образ и контейнер. 

        
files:

    -
        file:    linux-regex.md
        title: BASH. Регулярные выражения.
        meta_title: BASH. Регулярные выражения.
        meta_description: BASH. Регулярные выражения.
        meta_keywords: 'linux regex'
        desc: 
        order: 1

    -
        file:    dz.md
        title: Упражнения.
        meta_title: Упражнения.
        meta_description: Упражнения.
        meta_keywords: 'linux regex'
        desc: 
        order: 2
        

