from .registration import *
from .cabinet import *
from .profile import *
from .join_course import *
from .students import *
from .groups import *
from .invite import *
from .courses import *
from .course_detail import *
from .notify import *
