slug: js-marafon-quiz-react
name: Марафон. Фронтенд. Создание приложения "Викторина" на ReactJs.
meta_title:  Марафон. Фронтенд. Создание приложения "Викторина" на ReactJs.
meta_keywords:  Марафон. Фронтенд. Создание приложения "Викторина" на ReactJs.
meta_description:  Марафон. Фронтенд. Создание приложения "Викторина" на ReactJs.
is_active: true
tags: js javascript marafon quiz react
desc:
    Создаем онлайн викторину на ReactJs.

files:

    -
        file:     js-marafon-quiz-task.md
        title: Формулировка задачи.
        meta_title: Формулировка задачи.
        meta_description: Формулировка задачи.
        meta_keywords: Формулировка задачи.
        desc:
        youtube: https://www.youtube.com/embed/Vsiy1IntaMY
        order: 1


    -
        file:     js-quiz-react.md
        title: Создаем онлайн викторину на ReactJs.
        meta_title: Создаем онлайн викторину на ReactJs.
        meta_description: Создаем онлайн викторину на ReactJs.
        meta_keywords: Создаем онлайн викторину на ReactJs.
        desc:
        youtube: https://www.youtube.com/embed/rkR6y1bVTfw
        order: 2
        
    -
        file:     js-quiz-react-socket.md
        title: Работа с веб-сокетами.
        meta_title: Работа с веб-сокетами.
        meta_description: Работа с веб-сокетами.
        meta_keywords: Работа с веб-сокетами.
        desc:
        youtube: https://www.youtube.com/embed/RDcFQDBF7lg
        order: 3
        
    -
        file:     dz.md
        title: Задание викторины.
        meta_title: Задание викторины.
        meta_description: Задание викторины.
        meta_keywords: Задание викторины.
        desc:
        order: 4
        
        

        
        
        
