slug: dart-start
name: Фронтенд. Разработка карточной игры.
meta_title: Фронтенд. Разработка карточной игры.
meta_keywords: Фронтенд. Разработка карточной игры.
meta_description: Фронтенд. Разработка карточной игры.
is_active: true
tags: dart
desc:
    Создаем игру на jQuery.

files:

    -
        file:     card-game.md
        title: Создаем игру на jQuery.
        meta_title: Создаем игру на jQuery.
        meta_description: Создаем игру на jQuery.
        meta_keywords: Создаем игру на jQuery.
        desc:

