slug: linux-remote-developing
name: Удаленная разработка с Visual Studio Code.
meta_title: Удаленная разработка с Visual Studio Code.
meta_keywords: Удаленная разработка с Visual Studio Code.
meta_description: Удаленная разработка с Visual Studio Code.
is_active: true
tags: linux zsh
desc: 
    Настраиваем Vscode для удаленной разрабоки.

files:

    -
        file:    linux-zsh.md
        title: Удаленная разработка с Visual Studio Code.
        meta_title: Удаленная разработка с Visual Studio Code.
        meta_description: Удаленная разработка с Visual Studio Code.
        meta_keywords: 'linux vscode'
        desc: 

