slug: linux-bash-commands
name: Bash. Основные команды.
meta_title: Bash. Основные команды.
meta_keywords: Bash. Основные команды.
meta_description: Bash. Основные команды.
is_active: true
tags: linux bash stdin stdout
desc: |

        
files:

    -
        file:    bash-common-command.md
        title: Команды ввода-вывода.
        meta_title: Команды ввода-вывода.
        meta_description: Команды ввода-вывода.
        meta_keywords: 'bash'
        desc: 

    -
        file:    bash-file-system.md
        title: Bash. Команды файловой системы.
        meta_title: Bash. Команды файловой системы.
        meta_description: Bash. Команды файловой системы.
        meta_keywords: 'bash file system'
        desc: 

    -
        file:  bash-stdinout.md
        title: Потоки ввода-вывода.
        meta_title: Потоки ввода-вывода.
        meta_description:  Потоки ввода-вывода.
        meta_keywords: 'bash'
        desc: 

    -
        file:  dz.md
        title: Домашнее задание.
        meta_title: Домашнее задание.
        meta_description:  Домашнее задание.
        meta_keywords: 'bash'
        desc: 

