slug: python-video-bridge-start
name: Формулировка задачи. Старт проекта.
meta_title:  Формулировка задачи. Старт проекта.
meta_keywords:  Формулировка задачи. Старт проекта.
meta_description:  Формулировка задачи. Старт проекта.
is_active: true
tags: python video
created: 2021-02-24
desc:
      Планируем сервис для трансляции видео через протокол WebRTC.
files:

    -
        file:  1-python-video-bridge.md
        title: Сервис для видео-трансляций.
        meta_title: Сервис для видео-трансляций.
        meta_description: Сервис для видео-трансляций.
        meta_keywords: Сервис для видео-трансляций.
        desc: 
        order: 1
        youtube: https://www.youtube.com/embed/vT4daqPUTEQ

    
    -
        file:  3-start-jquery-ts.md
        title: Старт фронтенд приложения c jQuery, gulp и Typescript.
        meta_title: Старт фронтенд приложения c jQuery, gulp и Typescript.
        meta_description: Старт фронтенд приложения c jQuery, gulp и Typescript.
        meta_keywords: Старт фронтенд приложения c jQuery, gulp и Typescript.
        desc:
        order: 2
        created: 2021-02-20
        youtube: https://www.youtube.com/embed/pZYvLrcVQ0Q

    -
        file:  2-start-prj.md
        title: Стартуем проект.
        meta_title: Стартуем проект.
        meta_description: Стартуем проект.
        meta_keywords: Стартуем проект.
        desc:
        order: 3
        created: 2021-02-20
