slug: bash-aliases
name: Консоль. Алиасы. Переопределение встроеных функций.
meta_title:  Консоль. Алиасы. Переопределение встроеных функций.
meta_keywords:  Консоль. Алиасы. Переопределение встроеных функций.
meta_description: Консоль. Алиасы. Переопределение встроеных функций.
is_active: true
tags: linux bash alias venv
desc: 
        
files:

    -
        file:     'bash-alias.md'
        title: 'Алиасы.'
        meta_title: 'Алиасы.'
        meta_description:   'Алиасы.'
        meta_keywords: 'bash alias'
        desc: 

    -
        file:     sh-venv.md
        title: Активируем виртуальное окружени Python.
        meta_title: Активируем виртуальное окружени Python.
        meta_description:  Активируем виртуальное окружени Python.
        meta_keywords: 'bash alias'
        desc: 
