slug: python-video-bridge-nginx
name: Устанавливаем и конфигурируем прокси-сервер nginx.
meta_title: Устанавливаем и конфигурируем прокси-сервер nginx.
meta_keywords: Устанавливаем и конфигурируем прокси-сервер nginx.
meta_description: Устанавливаем и конфигурируем прокси-сервер nginx.
is_active: true
tags: python video django drf
created: 2021-02-28
desc:
      Контейнеризируем nginx.
files:

    -
        file:  7-nginx.md
        title: Устанавливаем и конфигурируем прокси-сервер nginx.
        meta_title: Устанавливаем и конфигурируем прокси-сервер nginx.
        meta_description: Устанавливаем и конфигурируем прокси-сервер nginx.
        meta_keywords: Устанавливаем и конфигурируем прокси-сервер nginx.
        desc: 
        order: 1
    
