slug: js-canvas-camera
name: Работа с веб камерой и холстом.
meta_title:  Работа с веб камерой и холстом.
meta_keywords:  Работа с веб камерой и холстом.
meta_description:  Работа с веб камерой и холстом.
is_active: true
tags: js javascript canvas camera
desc:
    Захватываем изображение с камеры и рисуем на холсте.

files:

    -
        file:     js-canvas-camera.md
        title: Работа с веб камерой и холстом.
        meta_title: Работа с веб камерой и холстом.
        meta_description: Работа с веб камерой и холстом.
        meta_keywords: Работа с веб камерой и холстом.
        desc:

    -
        file:     openvidu.md
        title: Трансляция видео с Openvidu.
        meta_title: Трансляция видео с Openvidu.
        meta_description: Трансляция видео с Openvidu.
        meta_keywords: Трансляция видео с Openvidu.
        desc:
        order: 2
        created: 2021-07-23

