slug: linux-zsh
name: Установка zsh.
meta_title: Установка zsh.
meta_keywords: Установка zsh.
meta_description: Установка zsh.
is_active: true
tags: linux zsh
desc: 
    Установка продвинутой версии коммандной строки.

files:

    -
        file:    linux-zsh.md
        title: Установка zsh.
        meta_title: Установка zsh.
        meta_description: Установка zsh.
        meta_keywords: 'linux zsh'
        desc: 

