slug: js-regex
name: Регулярные выражения.
meta_title: Регулярные выражения.
meta_keywords: Регулярные выражения.
meta_description: Регулярные выражения.
is_active: true
tags: js javascript regex
desc:
    Приемы проверки данных форм.

files:

    -
        file:     js-regex.md
        title: Регулярные выражения.
        meta_title: Регулярные выражения.
        meta_description: Регулярные выражения.
        meta_keywords: Регулярные выражения.
        desc:
        
