slug: python-video-bridge-calling
name: Вызов пользователя в чат.
meta_title: Вызов пользователя в чат.
meta_keywords: Вызов пользователя в чат.
meta_description: Вызов пользователя в чат.
is_active: true
tags: python video django drf
created: 2021-02-27
desc:
      Передаем запрос на видео подключение.
files:

    -
        file:  6-calling.md
        title: Вызов пользователя в чат.
        meta_title: Вызов пользователя в чат.
        meta_description: Вызов пользователя в чат.
        meta_keywords: Вызов пользователя в чат.
        desc: 
        order: 1
        youtube: https://www.youtube.com/embed/wwIRPxK59Q8
